project/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), nullable=False)

    password_hash = db.Column(db.String(255))
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
    def check_password(self, password):
        if self.password_hash is None:
            return False
        return check_password_hash(self.password_hash, password)
    
    role = db.Column(db.String(20), nullable=False)
    created_at = db.Column(db.DateTime, server_default=db.func.now())

    def __repr__(self):
        return '<User %r>' % self.username
    

project/__init__.py
from flask import Flask, request, jsonify, redirect, url_for, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user
import logging
import os
from dotenv import load_dotenv


db = SQLAlchemy()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)

    load_dotenv()

    app.config['MYSQL_HOST'] = os.getenv('MYSQL_HOST')
    app.config['MYSQL_USER'] = os.getenv('MYSQL_USER')
    app.config['MYSQL_PASSWORD'] = os.getenv('MYSQL_PASSWORD')
    app.config['MYSQL_DB'] = os.getenv('MYSQL_DB')

    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://' + os.getenv('MYSQL_USER') + \
        ':' + os.getenv('MYSQL_PASSWORD') + '@' + os.getenv('MYSQL_HOST') + '/' + os.getenv('MYSQL_DB')
    
    db.init_app(app)

    with app.app_context():
        from .models import User
        
        db.create_all()

        return app

project/blueprints/users.py
from flask import Blueprint, request, jsonify, redirect, url_for, render_template, flash
from project.models import User
from flask_mysqldb import MySQL

mysql = MySQL()

users = Blueprint('users', __name__)

@users.route('/users/<string:id>', methods=['GET'])
def get(id):
    cur = mysql.connection.cursor()
    cur.execute("SELECT * FROM users WHERE id=%s", (id,))
    data = cur.fetchone()
    cur.close()

    user = {
        'id': data[0],          
        'username': data[1],    
        'email': data[2],      
        'password': data[3],         
        'role': data[4]
    }
    return render_template('edit_user.html', user=user)


@users.route('/users', methods=['GET'])
def getAll():
    cur = mysql.connection.cursor()
    cur.execute("SELECT * FROM users")
    data = cur.fetchall()
    cur.close()

    return render_template('users.html', users=data)

@users.route('/add', methods=['POST'])
def add():
    username = request.form['username']
    email = request.form['email']
    password = request.form['password']
    role = request.form['role']

    new_user = User(username= username, email=email, role=role)
    new_user.set_password(password)
    cur = mysql.connection.cursor()
    cur.execute("INSERT INTO users (username, email, password_hash, role) VALUES (%s, %s, %s, %s)", (new_user.username, new_user.email, new_user.password_hash, new_user.role))

    mysql.connection.commit()
    return redirect(url_for('users.getAll'))

@users.route('/delete/<string:id>', methods=['GET'])
def delete(id):
    cur = mysql.connection.cursor()
    cur.execute("DELETE FROM users WHERE id=%s", (id,))
    mysql.connection.commit()
    return redirect(url_for('users.getAll'))

@users.route('/update/<string:id>', methods=['POST'])
def update(id):
    username = request.form['username']
    email = request.form['email']
    password = request.form['password']
    role = request.form['role']

    updated_user = User(username= username, email=email, role=role)
    updated_user.set_password(password)

    cur = mysql.connection.cursor()
    cur.execute("UPDATE users SET username=%s, email=%s, password_hash=%s, role=%s WHERE id=%s", (updated_user.username, updated_user.email, updated_user.password_hash, updated_user.role, id))

    mysql.connection.commit()
    return redirect(url_for('users.getAll'))

project/templates/edit_user.html
{% extends 'users.html' %}

{% block content %}
    <h2>Edit Users</h2>
    <form action="{{ url_for('users.update', id=user.id) }}" method="POST">
        <label for="username">Username:</label><br>
        <input type="text" id="username" name="username" value="{{ user.username }}"><br><br>
        <label for="email">Email:</label><br>
        <input type="text" id="email" name="email" value="{{ user.email }}"><br><br>
        <label for="password">Password:</label><br>
        <input type="text" id="password" name="password"><br><br>
        <label for="role">Role:</label><br>
        <input type="text" id="role" name="role" value="{{ user.role }}"><br><br>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

project/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Project</h1>
    <p>Welcome to the test site</p>
    <p>Login Here</p>
{% endblock %}

project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width-device-width, initial-scale=1.0">
        <title>Project Test</title>
        <link rel="stylesheet" href="../static/css/navbar_style.css">
    </head>
    <body> 
        <nav>
            <li><a href="/">Home</a></li>
            <li><a href="/users">Users</a></li>
        </nav>
        <br /> <br /> <br /> 
        <main>
            {% block content %}{% endblock %}
        </main>

        <footer>
            <!--<p>&copy; 2024</p>-->
        </footer>
    </body>
</html>

project/templates/users.html
{% extends 'layout.html' %}

{% block content %}
    <link rel="stylesheet" href="../static/css/style.css">
    <script src="{{ url_for('static', filename='js/users.js') }}"></script>
    <h2>Users List</h2>
    <table class="styled-table" name="users">
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Role</th>
            <th>Account Created On</th>
            <th>Actions</th>
        </tr>

        {% for row in users %}
        <tr>
            <td>{{row.1}}</td>
            <td>{{row.2}}</td>
            <td>{{row.4}}</td>
            <td>{{row.5}}</td>

            <td>
                <a href="/users/{{ row.0 }}">Edit</a>
                <a href="/delete/{{ row.0 }}" class="button" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <br><br>
    <h2>Add Users</h2>
    <form action="{{url_for('users.add')}}" method="POST">
        <label for="username">Username:</label><br>
        <input type="text" id="username" name="username"><br><br>
        <label for="email">Email:</label><br>
        <input type="text" id="email" name="email"><br><br>
        <label for="password">Password:</label><br>
        <input type="text" id="password" name="password"><br><br>
        <label for="role">Role:</label><br>
        <input type="text" id="role" name="role"><br><br>
        <input type="submit" value="Submit">
    </form>
    </div>

{% endblock %}